# Generated by Django 4.2 on 2024-12-10 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lyric', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lyric',
            name='is_published',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='published',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
